"""
main.py - Command-line driver for the Mini Compiler

Ties together every stage built so far into one pipeline:

    source (.mini file)
        --> Lexer            (lexer.py)
        --> Parser           (parser.py)              -> AST
        --> SemanticAnalyzer (semantic_analyzer.py)    -> checked AST
        --> IRGenerator      (ir_generator.py)         -> TAC
        --> optimize         (optimizer.py)            -> optimized TAC
        --> generate_bytecode(codegen.py)              -> bytecode
        --> VM               (vm.py)                   -> program output

Usage:
    python main.py path/to/program.mini
    python main.py path/to/program.mini --show-ir        # print TAC
    python main.py path/to/program.mini --show-bytecode  # print bytecode
    python main.py path/to/program.mini --show-all       # print every stage
"""

import sys
import argparse

from lexer import Lexer, LexerError
from parser import Parser, ParserError
from semantic_analyzer import SemanticAnalyzer, SemanticError
from ir_generator import IRGenerator, format_instructions
from optimizer import optimize
from codegen import generate_bytecode, format_bytecode
from vm import VM, VMError


def compile_and_run(source: str, show_ir=False, show_bytecode=False):
    # Stage 1: lexing
    tokens = Lexer(source).tokenize()

    # Stage 2: parsing
    ast = Parser(tokens).parse()

    # Stage 3: semantic analysis
    SemanticAnalyzer().analyze(ast)

    # Stage 4: IR generation
    ir = IRGenerator().generate(ast)

    # Stage 5: optimization
    optimized_ir = optimize(ir)
    if show_ir:
        print("=== Optimized Intermediate Representation (TAC) ===")
        print(format_instructions(optimized_ir))
        print()

    # Stage 6: code generation
    bytecode = generate_bytecode(optimized_ir)
    if show_bytecode:
        print("=== Bytecode ===")
        print(format_bytecode(bytecode))
        print()

    # Stage 7: execution
    print("=== Program output ===")
    VM(bytecode).run()


def main():
    arg_parser = argparse.ArgumentParser(description="Mini Compiler for MiniLang (.mini files)")
    arg_parser.add_argument("source_file", help="Path to a .mini source file")
    arg_parser.add_argument("--show-ir", action="store_true", help="Print the optimized TAC/IR")
    arg_parser.add_argument("--show-bytecode", action="store_true", help="Print the generated bytecode")
    arg_parser.add_argument("--show-all", action="store_true", help="Print IR and bytecode")
    args = arg_parser.parse_args()

    try:
        with open(args.source_file, "r") as f:
            source = f.read()
    except OSError as e:
        print(f"Could not read '{args.source_file}': {e}", file=sys.stderr)
        sys.exit(1)

    show_ir = args.show_ir or args.show_all
    show_bytecode = args.show_bytecode or args.show_all

    try:
        compile_and_run(source, show_ir=show_ir, show_bytecode=show_bytecode)
    except LexerError as e:
        print(f"Lexical error: {e}", file=sys.stderr)
        sys.exit(1)
    except ParserError as e:
        print(f"Syntax error: {e}", file=sys.stderr)
        sys.exit(1)
    except SemanticError as e:
        print(f"Semantic error: {e}", file=sys.stderr)
        sys.exit(1)
    except VMError as e:
        print(f"Runtime error: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
